version: '3.5'

services:

  quizdb:
    build:
      context: .
      dockerfile: Dockerfile.database
    restart: "no"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  quizserver:
    build: .
    restart: "no"
    ports:
      - 5000:8000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      FLASK_APP: src/app.py
    depends_on:
      - quizdb
