version: '3.5'

services:

  quizdb:
    image: postgres:15.2-alpine3.17
    restart: "no"
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  quizserver:
    build: .
    restart: "no"
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      FLASK_APP: src/app.py
    depends_on:
      - quizdb
