version: '3.5'

services:

  quizdb:
    image: postgres:15.2-alpine3.17
    restart: "no"
    ports:
      - 5555:5432
    # volumes:
    #   - ./local/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
