name: system-tests
run-name: ${{ github.actor }} is mixing it up like there's no tomorrow
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  run-system-tests:
    runs-on: ubuntu-latest
    env:
      PG_PASSWORD: ${{ secrets.PG_PW }}
      DATABASE_URL: ${{ secrets.DB_URI }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: upsie daisie
        uses: actions/checkout@v3
      - run: mkdir -p ${{ github.workspace }}/test-results
      - run: chmod 777 ${{ github.workspace }}/test-results
      - run: docker compose -f ${{ github.workspace }}/docker-compose-ci.yml up -d
      - run: docker pull juhanir/test-runner:0.1.0
      - run: PGPASSWORD=${{secrets.PG_PW}} ${{ github.workspace }}/scripts/reset_db.sh
      - run: |
          docker run --network="host" \
          --volume ${{ github.workspace }}/tests:/home/testrunner/tests \
          --volume ${{ github.workspace }}/test-results:/home/testrunner/test-results \
          juhanir/test-runner:0.1.0

      - name: Publish robot report
        uses: actions/upload-artifact@v3
        # if test-runner reports non-zero exit status, this should still run
        if: always()
        with:
          name: System test report
          path: ${{ github.workspace }}/test-results
